feat: Typescript version of AWS Lambda experiment project
ModusCreateOrg/engineering-experiments pull request #23
Opened 2022-02-25 17:16 UTC by zafar-saleem

Typescript version of AWS Lambda experiment project

2022-03-01 23:11 UTC, wesleyfuchter requested changes
- Both Rafael and me we tried to deploy and we faced issues. Please contact Rafael if you have questions about what we did;
- There are lots of unnecessary console.logs around the code, please make sure you toss them before raising the PR;
- Please toss all the files that are binary, you don’t need to replicate them from Rafael’s JS work;
- Please make sure you refactor the code to use Object-Oriented Programming. Using TypeScript you get the OOP power instead of the plain JS functional style;
- Many of the code in the classes are using still the functional approach instead of an object-oriented style that TypeScript allows you. Please review this to use clean code, solid and good OOP principles.
- You only need the folder zipper-file-async. Toss anything else;
- Please research how to use the AWS SDK types instead of creating your own types.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/list-zipped/interfaces.ts
> +interface IQueryStringParams {
Please do quick research on the AWS SDK types. It should have types for HTTPS Request/Response on its own, no need to have you rewriting this.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/list-zipped/interfaces.ts
> +export interface IApiList {
It should have all the methods of the handler class that implements it.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +class Uploader implements IUploader {
Many of the comments from the other class can be considered here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +      await this.s3.putObject({
Move this to a repository class.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +  extractFile(event: IEvent): IExtractFile {
Move this logic to a service/utility class.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +  async notifyUpload({ filename }: IFile) {
This should be moved to a class that exposes methods to communicate with a SQS queue.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/interfaces.ts
> +interface IHeaders {
Same as the other interfaces file.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/websocket/interfaces.ts
> +interface IBody {
Same as the other interfaces file.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/websocket/onconnect.ts
> +            await this.repository.put(putParams).promise();
Move this method to a repository class.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/websocket/onconnect.ts
> +class OnConnect implements IConnectionClass {
Please make sure you address all the other classes's comments here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/websocket/ondisconnect.ts
> +class OnDisconnect implements IConnectionClass {
Please make sure you address all the other classes's comments here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/websocket/onmessage.ts
> +        // let message: string;
Please toss these commented lines.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/index.ts
> +class Zipper {
Please make sure you address the other classes' comments here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/interfaces.ts
> +// export interface IConnectionClass {
Please make sure you address the other interface files' comments here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/websocket-client.ts
> +export default class WebSocketClient {
Please make sure you address the other classes' comments here as well.

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/zip-helper.ts
> +const pipe = promisify(pipeline);
Why you need global access here?

2022-03-01 23:11 UTC, wesleyfuchter commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/zip-helper.ts
> +
Static access methods are not the best strategy. Please refactor this helper class to be a functional object whose behavior os provides zipped files.

2022-03-02 15:09 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/list-zipped/index.ts
> +const FILES_TABLE = process.env.FILES_ZIPPED_TABLE;
The JavaScript version has the same concept here where these constants are outside of the class. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/list-zipped/index.js

2022-03-02 15:09 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/list-zipped/index.ts
> +export default handle;
If we take a look into the JavaScript version the approach is followed there as well. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/list-zipped/index.js

2022-03-02 15:13 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +class Uploader implements IUploader {
It's pretty much the same the JavaScript version has the constants outside of the class. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/uploader/index.js

2022-03-02 15:16 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +      await this.s3.putObject({
I kept it there because it in JavaScript version it part is in the same `uploader/index.js` file. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/uploader/index.js

2022-03-02 15:17 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +  extractFile(event: IEvent): IExtractFile {
Same like above I kept it there because the JavaScript version is in the same file as it suppose to be an experimented project as far as my understanding goes. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/uploader/index.js

2022-03-02 15:19 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/uploader/index.ts
> +  async notifyUpload({ filename }: IFile) {
Same like above as this seems to be an experimented project therefore, I presumed it was kept in the same js file in JavaScript version and for that reason I kept it there. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/uploader/index.js

2022-03-02 15:23 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/index.ts
> +class Zipper {
As it seems to be an experimental project therefore, I presumed that it was written that way in JavaScript version of this project and for that reason I left it as it. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/zipper/index.js

2022-03-02 15:25 UTC, zafar-saleem commented on serverless-node-app-typescript/serverless-framework/zipper-file-async/src/zipper/zip-helper.ts
> +const pipe = promisify(pipeline);
Again as it was written like that in JavaScript version as it is an experimental project therefore, I kept it global. https://github.com/ModusCreateOrg/js-coe-experiments/blob/master/serverless-node-app/serverless-framework/zipper-file-async/src/zipper/zip-helper.js

2022-03-15 18:48 UTC, wesleyfuchter approved these changes

2022-03-15 18:48 UTC, merged